### ISSUE TITLE
Could not install library to GlobalStorage

### ISSUE THREAD

**Issue by Kabron287** [platformio/platformio-home#1275]
1. Earlier it was not a problem. An **Install** button appeared to the right of the **Release** button and
it was possible to choose where the lib will be located.

Now this button changed to **Add to Project** and no options. 

It is not acceptable for me at all.
How to correct the problem?

2. I got info about available libraries updates. But the **Update** button is blocked. Only Reveal is active.

Thanks in advance,
Vladimir

**Comment by ivankravets** [comment]
Could you show a screenshot of "Updates" page?

Why do you need global libraries?

**Comment by Kabron287** [comment]
I'm used to doing this...
And note that I am being asked to install this library in a project for a different platform.
![Libs](https://user-images.githubusercontent.com/2493191/93083228-f55b0180-f69a-11ea-809a-64fdcd596c4a.jpg)

**Comment by ivankravets** [comment]
We added "Global libraries" 6 years ago to keep a similar workflow with Arduino IDE. This is the worst that people can architect. As a result, a ton of reports by developers due to conflicts between multiple projects.

We don't more follow Arduino IDE's workflow.  "CLI with -g option works", yes, you can use it. We will keep CLI compatible with our previous versions.

P.S: Why do you do this work manually? PlatformIO does this automatically for over 1,000,000 devs who use https://docs.platformio.org/en/latest/librarymanager/quickstart.html

**Comment by Kabron287** [comment]
I don't quite understand what kind of automation we are talking about. Before I added the global libraries, there was no way I could build the project WioWiFiAnalyzer at all, because absolutely idiotic errors appeared permanently one by one.
Also, platformio could not "automatically" find some libs at all. E.g. Arduino_GFX,  Seeed_Arduino_atUnified-1.0.0, Seeed_Arduino_atWiFi-1.0.0, esp-at-lib-develop, etc.

**Comment by ivankravets** [comment]
Could you provide a simple project to reproduce this issue where `lib_deps` does not work?

**Comment by Kabron287** [comment]
I do not use **lib_deps**.

**Comment by Kabron287** [comment]
Well, Ivan, you've convinced me.
I just ran into a very contagious libы from Seeed.
But the question is: usually I worked with folders and never created any projects.
Also, when I get code from Git, it placed in a folder.
If I need to add library in platformio it asced for which project?
I.e. I need to transform folder to project.
What is the way?

**Comment by Kabron287** [comment]
Ok I find
